Лабораторная работа №1
Выполнил студент группы БСТ1904 Муратов Никита
Вариант 13

Задание №1
1. Создать Jupyter Notebook со следующим наименованием: Lab1_Группа_ФИО.
2. Создать новую ячейку с помощью кнопки.
3. В созданной ячейке по указанной ниже форме заполните оглавление файла.
4. С помощью кнопки запустите выполнение всех ячеек.
5. После выполнения у вас должна отформатироваться ячейка с оглавлением и должен выполниться “Hello, World!”.

In [3]:
print("Hello, World!")

Hello, World!


Задание №2
Написать генератор случайных матриц(многомерных), который принимает
опциональные параметры m, n, min_limit, max_limit, где m и n указывают размер
матрицы, а min_lim и max_lim - минимальное и максимальное значение для
генерируемого числа .

In [27]:
%%time
import numpy as np
import time
import random
try:
    m = int(input("Введите количество строк m "))
except ValueError:
    m = 50
try:
    n = int(input("Введите число столбцов n "))
except ValueError:
    n = 50
try:
    min_lim = int(input("Введите минимальное число min_lim "))
except ValueError:
    min_lim = -250
try:
    max_lim = int(input("Введите максимальное число max_lim "))
except ValueError:
    max_lim = 1000 + 13
A = np.empty((m, n))
for i in range(m):
    for j in range(n):
        A[i, j] = random.randint(min_lim, max_lim)
print("Ваш массив: ")
print(A)

Введите количество строк m 5
Введите число столбцов n 5
Введите минимальное число min_lim 0
Введите максимальное число max_lim 100
Ваш массив: 
[[43. 12. 55. 45. 65.]
 [91. 72. 51. 28. 73.]
 [85. 61. 38. 69. 32.]
 [69. 14. 55. 58. 15.]
 [92. 48. 97. 93. 46.]]
Wall time: 4.11 s


Сортировка выбором

In [41]:
%%time
def selectionSort(A):
    for i in range(0, len(A) - 1):
        for j in range(i + 1, len(A)):
            if A[j] < A[i]:
                A[i], A[j] = A[j], A[i]

import numpy as np
B = np.empty(m*n)
C = np.empty((m, n))
z = 0
for x in range(m):
    for y in range(n):
        B[z] = A[x, y]
        z = z + 1
selectionSort(B)
z = 0
for x in range(m):
    for y in range(n):
        C[x, y] = B[z]
        z = z + 1
print(C)

[[-250. -250. -250. ... -214. -214. -213.]
 [-213. -213. -213. ... -187. -187. -186.]
 [-186. -186. -186. ... -163. -162. -162.]
 ...
 [ 948.  948.  948. ...  969.  970.  970.]
 [ 971.  972.  972. ...  992.  992.  993.]
 [ 993.  993.  993. ... 1012. 1012. 1013.]]
Wall time: 1.82 s


In [ ]:
Сортировка вставкой

In [8]:
%%time
def insertion_sort(A):
    for i in range(1, len(A)):
        temp = A[i]
        j = i - 1
        while (j >= 0 and temp < A[j]):
            A[j + 1] = A[j]
            j = j - 1
        A[j + 1] = temp

import numpy as np
B = np.empty(m*n)
C = np.empty((m, n))
z = 0
for x in range(m):
    for y in range(n):
        B[z] = A[x, y]
        z = z + 1
insertion_sort(B)
z = 0
for x in range(m):
    for y in range(n):
        C[x, y] = B[z]
        z = z + 1
print(C)

NameError: name 'A' is not defined

Сортировка обменом

In [39]:
%%time
def bubble(A):
    for j in range(len(A) - 1, 0, -1):
        for i in range(0, j):
            if A[i] > A[i + 1]:
                A[i], A[i + 1] = A[i + 1], A[i]

import numpy as np
B = np.empty(m*n)
C = np.empty((m, n))
z = 0
for x in range(m):
    for y in range(n):
        B[z] = A[x, y]
        z = z + 1
bubble(B)
z = 0
for x in range(m):
    for y in range(n):
        C[x, y] = B[z]
        z = z + 1
print(C)

[[-250. -250. -250. ... -214. -214. -213.]
 [-213. -213. -213. ... -187. -187. -186.]
 [-186. -186. -186. ... -163. -162. -162.]
 ...
 [ 948.  948.  948. ...  969.  970.  970.]
 [ 971.  972.  972. ...  992.  992.  993.]
 [ 993.  993.  993. ... 1012. 1012. 1013.]]
Wall time: 2.5 s


In [ ]:
Сортировка Шелла

In [46]:
%%time
def shell(A):
    step = len(A) // 2
    while step:
        for i, el in enumerate(A):
            while i >= step and A[i - step] > el:
                A[i] = A[i - step]
                i -= step
            A[i] = el
        step = 1 if step == 2 else int(step * 5.0 / 11)
        
import numpy as np
B = np.empty(m*n)
C = np.empty((m, n))
z = 0
for x in range(m):
    for y in range(n):
        B[z] = A[x, y]
        z = z + 1
shell(B)
z = 0
for x in range(m):
    for y in range(n):
        C[x, y] = B[z]
        z = z + 1
print(C)

[[-250. -250. -250. ... -214. -214. -213.]
 [-213. -213. -213. ... -187. -187. -186.]
 [-186. -186. -186. ... -163. -162. -162.]
 ...
 [ 948.  948.  948. ...  969.  970.  970.]
 [ 971.  972.  972. ...  992.  992.  993.]
 [ 993.  993.  993. ... 1012. 1012. 1013.]]
Wall time: 30 ms


In [ ]:
Пирамидальная сортировка

In [55]:
def heapsort(A):
    build_max_heap(A)
    for i in range(len(A) - 1, 0, -1):
        A[0], A[i] = A[i], A[0]
        max_heapify(A, index=0, size=i)
        
def parent(i):
    return (i - 1)//2
 
def left(i):
    return 2*i + 1
 
def right(i):
    return 2*i + 2
 
def build_max_heap(A):
    length = len(A)
    start = parent(length - 1)
    while start >= 0:
        max_heapify(A, index=start, size=length)
        start = start - 1
        
def max_heapify(A, index, size):
    l = left(index)
    r = right(index)
    if (l < size and A[l] > A[index]):
        largest = l
    else:
        largest = index
    if (r < size and A[r] > A[largest]):
        largest = r
    if (largest != index):
        A[largest], A[index] = A[index], A[largest]
        max_heapify(A, largest, size)

import numpy as np
B = np.empty(m*n)
C = np.empty((m, n))
z = 0
for x in range(m):
    for y in range(n):
        B[z] = A[x, y]
        z = z + 1
        
heapsort(B)
z = 0
for x in range(m):
    for y in range(n):
        C[x, y] = B[z]
        z = z + 1
print(C)





[[-250. -250. -250. ... -214. -214. -213.]
 [-213. -213. -213. ... -187. -187. -186.]
 [-186. -186. -186. ... -163. -162. -162.]
 ...
 [ 948.  948.  948. ...  969.  970.  970.]
 [ 971.  972.  972. ...  992.  992.  993.]
 [ 993.  993.  993. ... 1012. 1012. 1013.]]


In [ ]:
Турнирная сортировка

In [28]:
def TournamentSort(array):
    A= array.copy()
    for i in range(len(A)):
        tournamentSort(A[i])
    return A
def tournamentSort(A):
    tree = [None] * 2 * (len(A) + len(A) % 2)
    index = len(tree) - len(A) - len(A) % 2

    for i, v in enumerate(A):
        tree[index + i] = (i, v)

    for j in range(len(A)):
        n = len(A)
        index = len(tree) - len(A) - len(A) % 2
        while index > -1:
            n = (n + 1) // 2
            for i in range(n):
                i = max(index + i * 2, 1) 
                if tree[i] != None and tree[i + 1] != None:
                    if tree[i][1] < tree[i + 1][1]:
                        tree[i // 2] = tree[i]
                    else:
                        tree[i // 2] = tree[i + 1]
                else:
                    tree[i // 2] = tree[i] if tree[i] != None else tree[i + 1]
            index -= n

        index, x = tree[0]
        A[j] = x
        tree[len(tree) - len(A) - len(A) % 2 + index] = None

import numpy as np
B = np.empty(m*n)
C = np.empty((m, n))
z = 0
for x in range(m):
    for y in range(n):
        B[z] = A[x, y]
        z = z + 1
tournamentSort(B)
z = 0
for x in range(m):
    for y in range(n):
        C[x, y] = B[z]
        z = z + 1
print(C)

[[12. 14. 14. 15. 15.]
 [28. 28. 32. 32. 38.]
 [38. 43. 45. 48. 48.]
 [51. 55. 55. 58. 58.]
 [61. 61. 65. 69. 69.]]


In [ ]:
Быстрая сортировка

In [24]:
def quick(A, start, end):
    if end - start > 1:
        p = partition(A, start, end)
        quick(A, start, p)
        quick(A, p + 1, end)
 
 
def partition(A, start, end):
    pivot = A[start]
    i = start + 1
    j = end - 1
 
    while True:
        while (i <= j and A[i] <= pivot):
            i = i + 1
        while (i <= j and A[j] >= pivot):
            j = j - 1
 
        if i <= j:
            A[i], A[j] = A[j], A[i]
        else:
            A[start], A[j] = A[j], A[start]
            return j
 
 
import numpy as np
B = np.empty(m*n)
C = np.empty((m, n))
z = 0
for x in range(m):
    for y in range(n):
        B[z] = A[x, y]
        z = z + 1        
quick(B, 0, len(A))
z = 0
for x in range(m):
    for y in range(n):
        C[x, y] = B[z]
        z = z + 1
print(C)

[[ 17.  20.  23.  49.  50.  74. 159. 162. 164. 223. 281. 335. 345. 380.
  445. 454. 479. 620. 690. 758. 784. 965. 971. 988. 993.]
 [568. 988. 486. 589.  32.  65. 740. 109. 374. 243. 433.  11. 635. 838.
   37. 302. 858. 168. 452. 681. 478. 299. 932. 573. 356.]
 [600. 292. 320. 494. 694.   4. 136. 448. 549. 618.  81. 825. 378. 825.
  775. 566. 396. 379. 537. 571. 160. 917. 318. 663. 598.]
 [390. 285.   7. 943. 592. 634. 981. 777. 887. 462. 192. 459. 972. 518.
  533. 263. 606. 550. 661. 223. 820.  74. 927. 802. 444.]
 [664. 523. 582. 188. 198. 971. 198. 797. 672. 665. 625. 298. 107. 976.
  606. 419. 522. 883. 788. 286. 919. 608.  97. 429. 460.]
 [441. 156. 809. 203. 726. 702. 303. 433. 142. 676. 862. 791. 332. 288.
  507. 366. 343. 250. 664. 355. 418. 648.  10. 630. 546.]
 [344. 308. 114. 898. 604.  62. 232. 692. 553. 247. 237. 940. 526. 422.
  963. 977.  28. 791. 470. 360. 213. 342. 915. 734. 115.]
 [ 27. 818. 619. 316. 851. 493. 235. 891.  40. 938. 344. 376. 505. 862.
   36. 870. 346. 5